CREATE TABLE al_player_review (id INTEGER PRIMARY KEY AUTOINCREMENT, "year" INTEGER, "league" TEXT, "player" TEXT, "team" TEXT, "pos" TEXT, "g" INTEGER, "ab" INTEGER, "r" INTEGER, "h" INTEGER, "2b" INTEGER, "3b" INTEGER, "hr" INTEGER, "rbi" INTEGER, "bb" INTEGER, "so" INTEGER, "sb" INTEGER, "cs" INTEGER, "avg" REAL, "obp" REAL, "slg" REAL, "w" INTEGER, "l" INTEGER, "era" REAL, "sv" INTEGER, "sho" INTEGER, "ip" REAL, "er" INTEGER, "k" INTEGER, "player_link" TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX idx_al_player_review_year ON al_player_review(year);
CREATE INDEX idx_al_player_review_team ON al_player_review(team);
CREATE TABLE al_pitcher_review (id INTEGER PRIMARY KEY AUTOINCREMENT, "year" INTEGER, "league" TEXT, "player" TEXT, "team" TEXT, "pos" TEXT, "g" INTEGER, "ab" INTEGER, "r" INTEGER, "h" INTEGER, "2b" INTEGER, "3b" INTEGER, "hr" INTEGER, "rbi" INTEGER, "bb" INTEGER, "so" INTEGER, "sb" INTEGER, "cs" INTEGER, "avg" REAL, "obp" REAL, "slg" REAL, "w" INTEGER, "l" INTEGER, "era" REAL, "sv" INTEGER, "sho" INTEGER, "ip" REAL, "er" INTEGER, "k" INTEGER, "player_link" TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_al_pitcher_review_year ON al_pitcher_review(year);
CREATE INDEX idx_al_pitcher_review_team ON al_pitcher_review(team);
CREATE TABLE al_team_standings (id INTEGER PRIMARY KEY AUTOINCREMENT, "year" INTEGER, "league" TEXT, "division" TEXT, "team" TEXT, "w" INTEGER, "l" INTEGER, "wp" REAL, "gb" TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_al_team_standings_year ON al_team_standings(year);
CREATE INDEX idx_al_team_standings_team ON al_team_standings(team);
CREATE TABLE nl_player_review (id INTEGER PRIMARY KEY AUTOINCREMENT, "year" INTEGER, "league" TEXT, "player" TEXT, "team" TEXT, "pos" TEXT, "g" INTEGER, "ab" INTEGER, "r" INTEGER, "h" INTEGER, "2b" INTEGER, "3b" INTEGER, "hr" INTEGER, "rbi" INTEGER, "bb" INTEGER, "so" INTEGER, "sb" INTEGER, "cs" INTEGER, "avg" REAL, "obp" REAL, "slg" REAL, "w" INTEGER, "l" INTEGER, "era" REAL, "sv" INTEGER, "sho" INTEGER, "ip" REAL, "er" INTEGER, "k" INTEGER, "player_link" TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_nl_player_review_year ON nl_player_review(year);
CREATE INDEX idx_nl_player_review_team ON nl_player_review(team);
CREATE TABLE nl_pitcher_review (id INTEGER PRIMARY KEY AUTOINCREMENT, "year" INTEGER, "league" TEXT, "player" TEXT, "team" TEXT, "pos" TEXT, "g" INTEGER, "ab" INTEGER, "r" INTEGER, "h" INTEGER, "2b" INTEGER, "3b" INTEGER, "hr" INTEGER, "rbi" INTEGER, "bb" INTEGER, "so" INTEGER, "sb" INTEGER, "cs" INTEGER, "avg" REAL, "obp" REAL, "slg" REAL, "w" INTEGER, "l" INTEGER, "era" REAL, "sv" INTEGER, "sho" INTEGER, "ip" REAL, "er" INTEGER, "k" INTEGER, "player_link" TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_nl_pitcher_review_year ON nl_pitcher_review(year);
CREATE INDEX idx_nl_pitcher_review_team ON nl_pitcher_review(team);
CREATE TABLE nl_team_standings (id INTEGER PRIMARY KEY AUTOINCREMENT, "year" INTEGER, "league" TEXT, "division" TEXT, "team" TEXT, "w" INTEGER, "l" INTEGER, "wp" REAL, "gb" TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_nl_team_standings_year ON nl_team_standings(year);
CREATE INDEX idx_nl_team_standings_team ON nl_team_standings(team);
